### ISSUE TITLE
prettier-standard linting errors

### ISSUE THREAD

**Issue by Windvis** [sheerun/prettier-standard#80] opened 2019-04-10 14:52 UTC
Due to the project's title (`Prettier and standard brought together! <3`) I assumed we didn't need to install and run standard for its linting functionality. I did some testing and it seems like prettier-standard does not output any linting errors.

Are we supposed to run standard alongside prettier-standard?

**Comment by sheerun** [comment] 2019-04-10 16:01
It's duplicate of #17

**Closed by sheerun** 2019-04-10 16:01 UTC

**Comment by Windvis** [comment] 2019-04-11 07:09
Thanks for the link! I'm still not sure what would be the best way to also get Standard's linting functionality. Maybe some more clarification can be added to the readme file? It looks like I'm not the only one who misunderstood what prettier-standard actually does (and doesn't).

**Comment by sheerun** [comment] 2019-04-11 07:50
I thought it was pretty clear with "While standard is a linter, prettier-standard is a formatter"? #17 is not about misunderstanding but adding extra functionality

**Comment by baylin87** [comment] 2020-06-05 02:25
@sheerun prettier-standard seems deps `eslint` when I use `--lint` ?

package.json
```json
{
    "scripts": {
        "prettier": "prettier-standard --lint"
    },
    "dependencies": {
        // no eslint
    },
    "devDependencies": {
        // no eslint yet
        "babel-eslint": "^10.0.3",
        "prettier-standard": "^16.3.0",
    },
}
```

`npm run prettier`

output:
```bash
✖ prettier-standard --lint found some errors. Please fix them and try committing again.
helpers/remix.js 560ms


/Users/xx/coding/helpers/remix.js
  0:0  error  Parsing error: Cannot find module 'eslint'
Require stack:
- /Users/xx/coding/node_modules/babel-eslint/lib/require-from-eslint.js
- /Users/xx/coding/node_modules/babel-eslint/lib/analyze-scope.js
- /Users/xx/coding/node_modules/babel-eslint/lib/parse-with-scope.js
- /Users/xx/coding/node_modules/babel-eslint/lib/index.js
- /Users/xx/coding/node_modules/prettier-standard/node_modules/eslint/lib/cli-engine/config-array-factory.js
- /Users/xx/coding/node_modules/prettier-standard/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js
- /Users/xx/coding/node_modules/prettier-standard/node_modules/eslint/lib/cli-engine/cli-engine.js
- /Users/xx/coding/node_modules/prettier-standard/node_modules/eslint/lib/cli-engine/index.js
- /Users/xx/coding/node_modules/prettier-standard/node_modules/eslint/lib/api.js
- /Users/xx/coding/node_modules/prettier-standard/src/index.js
- /Users/xx/coding/node_modules/prettier-standard/src/cli.js

✖ 1 problem (1 error, 0 warnings)
````
